python3 ConsumerAtecaHume.py &
python3 ConsumerAtecaLumi.py &
python3 ConsumerAtecaRuido.py &
python3 ConsumerAtecaTemp.py &
python3 ConsumerAula142Hume.py &
python3 ConsumerAula142Lumi.py &
python3 ConsumerAula142Ruido.py &
python3 ConsumerAula142Temp.py &
python3 ConsumerAula145Hume.py &
python3 ConsumerAula145Lumi.py &
python3 ConsumerAula145Ruido.py &
python3 ConsumerAula145Temp.py &
python3 ConsumerAula149Hume.py &
python3 ConsumerAula149Lumi.py &
python3 ConsumerAula149Ruido.py &
python3 ConsumerAula149Temp.py &
python3 ConsumerCiscoHume.py &
python3 ConsumerCiscoLumi.py &
python3 ConsumerCiscoRuido.py &
python3 ConsumerCiscoTemp.py &
python3 ConsumerAtecaCamara.py &
python3 ConsumerAtecaCamara.py &
